-- -----------------------------------------------------
-- PostgreSQL bootstrap schema for Ildkule
-- Mirrors the active MySQL bootstrap surface as closely as possible.
-- -----------------------------------------------------

DROP TABLE IF EXISTS user_review CASCADE;
DROP TABLE IF EXISTS log_station CASCADE;
DROP TABLE IF EXISTS observation_trail_point CASCADE;
DROP TABLE IF EXISTS event_res_entry CASCADE;
DROP TABLE IF EXISTS observation_cam_data CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS cam CASCADE;
DROP TABLE IF EXISTS station CASCADE;
DROP TABLE IF EXISTS manual_input_observation CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE IF NOT EXISTS "user" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NULL UNIQUE,
  password VARCHAR(255) NULL,
  role VARCHAR(255) DEFAULT 'ROLE_USER',
  user_level VARCHAR(255) DEFAULT '0',
  tutorial_completed BOOLEAN DEFAULT FALSE,
  confirmed BOOLEAN DEFAULT FALSE,
  confirm_token VARCHAR(1000),
  password_reset_token VARCHAR(1000),
  password_reset_request_time TIMESTAMP NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS manual_input_observation (
  id INTEGER NOT NULL,
  latitude REAL NULL,
  longitude REAL NULL,
  date_time TIMESTAMP NULL,
  first_recorded_direction VARCHAR(45) NULL,
  first_recorded_altitude VARCHAR(45) NULL,
  last_recorded_direction VARCHAR(45) NULL,
  last_recorded_altitude VARCHAR(45) NULL,
  duration REAL NULL,
  color VARCHAR(45) NULL,
  brightness VARCHAR(45) NULL,
  description VARCHAR(280) NULL,
  image_file VARCHAR(45) NULL,
  users_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_manual_input_observation_users
    FOREIGN KEY (users_id)
    REFERENCES "user" (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS fk_manual_input_observation_users_idx ON manual_input_observation (users_id);

CREATE TABLE IF NOT EXISTS station (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  station_name VARCHAR(100) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cam (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  station_id INTEGER NOT NULL,
  cam_name VARCHAR(100) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT unique_cam_cam_name_station_id UNIQUE (cam_name, station_id),
  CONSTRAINT cam_ibfk_1
    FOREIGN KEY (station_id)
    REFERENCES station (id)
);
CREATE INDEX IF NOT EXISTS cam_station_id_idx ON cam (station_id);

CREATE TABLE IF NOT EXISTS event (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  datetimetag VARCHAR(32) NOT NULL,
  location VARCHAR(100) NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  track_startheight REAL NULL,
  track_endheight REAL NULL,
  track_groundtrack REAL NULL,
  track_course REAL NULL,
  track_incidence REAL NULL,
  track_speed REAL NULL,
  track_speed_source VARCHAR(100) NULL,
  track_startlat REAL NULL,
  track_startlong REAL NULL,
  track_endlat REAL NULL,
  track_endlong REAL NULL,
  fit_error REAL NULL,
  fit_quality REAL NULL,
  radiant_ra REAL NULL,
  radiant_dec REAL NULL,
  radiant_ecl_long REAL NULL,
  radiant_ecl_lat REAL NULL,
  radiant_shower VARCHAR(100) NULL,
  radiant_zenith_attractor VARCHAR(100) NULL,
  timestamp VARCHAR(100) NULL,
  date TIMESTAMP NULL,
  camera_confirmed SMALLINT DEFAULT NULL,
  user_confirmed SMALLINT DEFAULT NULL,
  first_seen_at TIMESTAMP NOT NULL,
  last_seen_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deletion_reason VARCHAR(50) NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_event_datetimetag UNIQUE (datetimetag)
);
CREATE INDEX IF NOT EXISTS event_date_idx ON event (date DESC, id DESC);
CREATE INDEX IF NOT EXISTS event_public_date_idx
  ON event (date DESC, id DESC)
  WHERE is_deleted = FALSE AND (user_confirmed IS NULL OR user_confirmed <> 0);

CREATE TABLE IF NOT EXISTS observation_cam_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL,
  cam_id INTEGER NOT NULL,
  observation_key VARCHAR(255) NOT NULL,
  source_hash CHAR(64) NOT NULL,
  event_start_utc TIMESTAMP NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_seen_at TIMESTAMP NOT NULL,
  last_seen_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deletion_reason VARCHAR(50) NULL,
  trail_frames INTEGER NULL,
  trail_duration REAL NULL,
  trail_slope REAL NULL,
  trail_offset REAL NULL,
  trail_speed REAL NULL,
  trail_correlation REAL NULL,
  trail_positions TEXT NULL,
  trail_timestamps TEXT NULL,
  trail_coordinates TEXT NULL,
  trail_ams_coords TEXT NULL,
  trail_centroid TEXT NULL,
  trail_centroid2 TEXT NULL,
  trail_gnomonic TEXT NULL,
  trail_midpoint VARCHAR(1000) NULL,
  trail_arc REAL NULL,
  trail_brightness TEXT NULL,
  trail_dct_midpoint INTEGER NULL,
  trail_dct TEXT NULL,
  trail_size TEXT NULL,
  trail_frame_brightness TEXT NULL,
  video_start TIMESTAMP NULL,
  video_end TIMESTAMP NULL,
  video_wallclock TIMESTAMP NULL,
  video_heigth INTEGER NULL,
  video_raw INTEGER NULL,
  video_flash INTEGER NULL,
  config_swidth INTEGER NULL,
  config_sheight INTEGER NULL,
  config_swdec INTEGER NULL,
  config_downscale_thr INTEGER NULL,
  config_mintrail_sec REAL NULL,
  config_maxtrail_sec REAL NULL,
  config_mintrail REAL NULL,
  config_maxtrail REAL NULL,
  config_minspeed REAL NULL,
  config_maxspeed REAL NULL,
  config_minspeed_kms REAL NULL,
  config_maxspeed_kms REAL NULL,
  config_leveltest INTEGER NULL,
  config_numspots INTEGER NULL,
  config_brightness INTEGER NULL,
  config_flash_thr REAL NULL,
  config_lookahead INTEGER NULL,
  config_exit INTEGER NULL,
  config_peak REAL NULL,
  config_filter INTEGER NULL,
  config_dct_threshold REAL NULL,
  config_correlation REAL NULL,
  config_spacing_correlation REAL NULL,
  config_gnomonic_correlation REAL NULL,
  config_nothreads INTEGER NULL,
  config_lastreport_ts BIGINT NULL,
  config_ts_future INTEGER NULL,
  config_snapshot_interval INTEGER NULL,
  config_snapshot_integration INTEGER NULL,
  config_log_file VARCHAR(45) NULL,
  config_mask_file VARCHAR(45) NULL,
  config_max_file VARCHAR(45) NULL,
  config_save_file VARCHAR(45) NULL,
  config_pto_file VARCHAR(45) NULL,
  config_pto_scale REAL NULL,
  config_pto_width REAL NULL,
  config_pto_height REAL NULL,
  config_execute VARCHAR(45) NULL,
  config_event_dir VARCHAR(45) NULL,
  config_snapshot_dir VARCHAR(45) NULL,
  summary_latitude REAL NULL,
  summary_longitude REAL NULL,
  summary_elevation INTEGER NULL,
  summary_timestamp TIMESTAMP NULL,
  summary_startpos REAL NULL,
  summary_endpos REAL NULL,
  summary_duration REAL NULL,
  summary_sunalt REAL NULL,
  summary_recalibrated INTEGER NULL,
  summary_meteor_probability REAL NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_observation_key UNIQUE (observation_key),
  CONSTRAINT observation_cam_data_ibfk_1
    FOREIGN KEY (event_id)
    REFERENCES event (id),
  CONSTRAINT observation_cam_data_ibfk_2
    FOREIGN KEY (cam_id)
    REFERENCES cam (id)
);
CREATE INDEX IF NOT EXISTS observation_cam_data_event_id_idx ON observation_cam_data (event_id);
CREATE INDEX IF NOT EXISTS observation_cam_data_cam_id_idx ON observation_cam_data (cam_id);
CREATE INDEX IF NOT EXISTS observation_cam_data_observation_key_idx ON observation_cam_data (observation_key);

CREATE TABLE IF NOT EXISTS event_res_entry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL,
  line_no INTEGER NOT NULL,
  entry_type VARCHAR(20) NOT NULL,
  label VARCHAR(20) NULL,
  long1 REAL NULL,
  lat1 REAL NULL,
  long2 REAL NULL,
  lat2 REAL NULL,
  height REAL NULL,
  raw_line VARCHAR(500) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_event_res_entry_line UNIQUE (event_id, line_no),
  CONSTRAINT event_res_entry_ibfk_1
    FOREIGN KEY (event_id)
    REFERENCES event (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS event_res_entry_event_id_idx ON event_res_entry (event_id);

CREATE TABLE IF NOT EXISTS observation_trail_point (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  observation_id INTEGER NOT NULL,
  frame_index INTEGER NOT NULL,
  pixel_x REAL NULL,
  pixel_y REAL NULL,
  event_timestamp_us BIGINT NULL,
  coord_long REAL NULL,
  coord_lat REAL NULL,
  ams_coord_long REAL NULL,
  ams_coord_lat REAL NULL,
  centroid_coord_long REAL NULL,
  centroid_coord_lat REAL NULL,
  centroid2_coord_long REAL NULL,
  centroid2_coord_lat REAL NULL,
  gnomonic_x REAL NULL,
  gnomonic_y REAL NULL,
  brightness REAL NULL,
  dct REAL NULL,
  size REAL NULL,
  frame_brightness REAL NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_observation_trail_point_frame UNIQUE (observation_id, frame_index),
  CONSTRAINT observation_trail_point_ibfk_1
    FOREIGN KEY (observation_id)
    REFERENCES observation_cam_data (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS observation_trail_point_observation_id_idx ON observation_trail_point (observation_id);

CREATE TABLE IF NOT EXISTS log_station (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  station_name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  log_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_review (
  user_id INTEGER NOT NULL,
  confirmed SMALLINT NULL,
  event_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, event_id),
  CONSTRAINT fk_users_has_observation_cam_data_users1
    FOREIGN KEY (user_id)
    REFERENCES "user" (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_user_review_event1
    FOREIGN KEY (event_id)
    REFERENCES event (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS fk_users_has_observation_cam_data_users1_idx ON user_review (user_id);
CREATE INDEX IF NOT EXISTS fk_user_review_event1_idx ON user_review (event_id);
